### ISSUE TITLE
#10 - Desenhar layout de tela de login

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#10]
Está será a tela principal do sistema. Está tela a principio irá conter dois campos com entrada de dados uma será para o login e outro para a senha. E um botão para entrar.

**Comment by rhuants** [comment]
Finalizado https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fsearch%2Fgato-computadora-gifs&psig=AOvVaw0Ef08Hxwb2kQSo_A74Y7dp&ust=1636569004702000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCLjK2-L0i_QCFQAAAAAdAAAAABAD

**Comment by rhuants** [comment]
https://tenor.com/view/gato-digitando-cat-kitten-kitty-gif-17761219

**Comment by rhuants** [comment]
Finalizado

![](https://c.tenor.com/rkY5QA5c3VAAAAAC/gato-digitando.gif)
