### ISSUE TITLE
#13 - Desenhar a tela cidades

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#13]
Desenhar a tela cidades que deve conter o codigo do IBGE, Descrição e UF. Além dos campos Cadastrar, Alterar, Excluir, Limpar, Fechar e Pesquisar. Também deve conter a tabela para buscar os dados do banco.

**Comment by Lukaex** [comment]
Concluída parcialmente, apenas necessário adicionar uma tabela por meu NetBeans não mostra opção para criar uma tabela.
