### ISSUE TITLE
#14 - Desenhar a tela Tipos Sanguíneos.

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#14]
Nesta tela deve conter o código, descrição, estoque, estoque mínimo e fator RH. O fator Rh pode ser um combobox com as informações fixas, neste caso Positivo e Negativo. Além dos campos Cadastrar, Alterar, Excluir, Limpar, Fechar e Pesquisar. Também deve conter a tabela para buscar os dados do banco.

**Comment by GabrielBalestrin** [comment]
finalizado
