### ISSUE TITLE
#15 - Desenhar tela de entidades

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#15]
Na tela de entidades deve conter o código, o nome da entidade que irá receber o sangue doado, endereço e cidade. A cidade será um combobox que irá buscar da tabela cidades. Além dos campos Cadastrar, Alterar, Excluir, Limpar, Fechar e Pesquisar. Também deve conter a tabela para buscar os dados do banco.

**Comment by davidcebolinha** [comment]
Finalizado
