### ISSUE TITLE
#20 - Na tela principal do sistema de ter trazer os agendamentos do dia

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#20]
Dentro da tela principal na tabela, trazer os agendamentos do dia.

**Comment by rhuants** [comment]
Concluído

https://c.tenor.com/rkY5QA5c3VAAAAAC/gato-digitando.gif

**Comment by rhuants** [comment]
[https://camo.githubusercontent.com/ac6826cbcabeecf67f6df206254fa9d770c8071a6d83bfe9cd743873d1d20515/68747470733a2f2f632e74656e6f722e636f6d2f726b59355141356333564141414141432f6761746f2d6469676974616e646f2e676966](url)
