### ISSUE TITLE
#28 - Desenvolver a função para cadastrar cidades.

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#28]
Criar função cadastrar cidades, criando dentro da classe DAO.

**Comment by davidcebolinha** [comment]
Criada a Função de Cadastrar Cidades, corrigir e ver se tudo está funcionando

**Comment by omenegazzi** [comment]
A principio está ok. Apenas lembra de colocar a função na tela de cadastro de cidades no botão para testar se a função está funcionando.

**Comment by davidcebolinha** [comment]
Função cadastrar cidades integrada com o botão do form cidades e tabela configurada para pesquisa e clique
