### ISSUE TITLE
#36 - Desenvolver função para alterar tipos sanguíneos

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#36]
Criar função para alterar os tipos sanguíneos cadastrados. Deverá ser criado dentro da classe TipoSanguineoDAO que fica no pacote Controller_DAO.

**Comment by omenegazzi** [comment]
@girardigian @Scotinski Vocês pegaram esta atividade pra fazer? Precisa de alguma ajudar?

**Comment by Scotinski** [comment]
Ficamos com um pouco de dificuldade pois estava dando alguns erros na hora de alterar, vamos dar mais uma revisada próxima aula.
