### ISSUE TITLE
#48 - Desenvolver a função para cadastrar colaboradores.

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#46]
Criar função cadastrar doadores, criando dentro da classe ColaboradoresDao.

**Comment by omenegazzi** [comment]
**Precisa realizar alguns ajustes:**  

- No model Colaboradores.java o id_cidade não é int ele é do tipo cidade, ou seja, ficaria assim:  private Cidade id_cidade; Porém pra que isso acontece, alguém deve criar a model Cidade antes.  
- No Dao na class ColaboradoresDao, o método cadastrar depois que alterar o tipo do id_cidade, na primeiro linha do stmt ficará algo neste sentido: stmt.setInt(1,c.getId_cidade().getcodigo);

**Comment by gabrielsuui** [comment]
Blz professor, entao eu tb vou ter q alterar no pesquisar e no listar, ja
que eu fiz parecido com esse.

Em qua., 10 de nov. de 2021 10:04, Diego Menegazzi ***@***.***>
escreveu:

**Comment by omenegazzi** [comment]
A principio a função está ok. Já fiz o merge com a develop. Só precisa testar a função com a a tela, quando clicar no botão cadastrar deve salvar no banco.
