### ISSUE TITLE
#50 - Desenvolver função para alterar colaboradores

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#48]
Criar função para alterar os colaboradores cadastrados. Deverá ser criado dentro da classe ColaboradoresDao que fica no pacote Controller_DAO.

**Comment by omenegazzi** [comment]
@anaspuldaro fui procurar a função do alterar no Dao e não encontrei. Eu não sei se você já fez, caso já tenha feito. Só precisa enviar para o Github que eu junto aqui. Se tiver alguma dúvida só avisar que eu te ajudo.

**Comment by anaspuldaro** [comment]
Eu fiz sim, oque eu preciso fazer para enviar

**Comment by anaspuldaro** [comment]
Ontem tentei duas vezes e hoje novamente, eu faço o login  e ele volta a
pedir novamente
[image: image.png]

Em qua., 1 de dez. de 2021 às 12:02, Diego Menegazzi <
***@***.***> escreveu:
