### ISSUE TITLE
#53 - Criar o model para classe doações

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#51]
A classe pode ser criada dentro do pacote model pode ser com o nome de doacoes. Essa classe irá conter os gettes e setters.

**Comment by adgunther** [comment]
model  pronto

**Comment by omenegazzi** [comment]
**Precisa fazer alguns ajustes no Model Doacoes.java:** 

- a variável private int codigo pode ser excluída, pois já existe um id_doacao abaixo;  
- a variável id_doaçao não pode estar com "ç" deve ser id_doacao;  
-  a variável id_doador não é string ela é do tipo doador ficaria algo neste sentido: private Doador id_doador. Mas só é possível depois que alguém a classe Doador.java;   
- a variável id_tipo_sanguineo não é string ela é do tipo TipoSanguineo ficaria algo neste sentido: private TipoSanguineo id_tipo_sanguineo. Mas só é possível depois que alguém a classe TipoSanguineo.java;
- a variável id_colaborador não é string ela é do tipo Colaboradores ficaria algo neste sentido: private Colaboradores id_colaborador. Mas só é possível depois que alguém a classe Colaboradores.java.

**Comment by adgunther** [comment]
criado e alterado model doacoes
