### ISSUE TITLE
#59 - Criar o model para classe agendamentos

### ISSUE THREAD

**Issue by omenegazzi** [omenegazzi/senac-sistema-hemosc#57]
A classe pode ser criada dentro do pacote model pode ser com o nome de agendamentos. Essa classe irá conter os gettes e setters.

**Comment by adgunther** [comment]
criado model agendamentos

**Comment by omenegazzi** [comment]
**Precisa realizar alguns ajustes:** 

- Alterar no nome da classe e deixar a primeira letra maiúscula, exemplo: Agendamentos.java;
- A variável private int código, pode ser excluída pois já possui o id_agendamento;
- A variável id_agendamento não é string é int;
- A variável id_doador não é String é do tipo Doador, ficaria algo neste sentido:  private Doador id_doador, mas é preciso que a classe Doadores.java esteja criada;
- Realizar a indentação do código para deixar alinhado: Para isso, você pode ir no menu Código-Fonte > Formatar.

**Comment by adgunther** [comment]
Alterado e criado model agendamentos
